name: Build (Windows)

on:
    workflow_dispatch:
    push:
        branches: ["main"]
        paths:
            - "src/**"
            - "lib/**"
    pull_request:
        branches: ["main"]
        paths:
            - "src/**"
            - "lib/**"

jobs:
    Build:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v4

            # # Fix executables
            # - name: Make executable shell scripts
            #   run: sudo chmod +x ./build_tools/*.sh

            # # Build libraries
            # - name: Make Libraries
            #   run: make libs

            # # Build binary
            # - name: Build Mercury Binary
            #   run: sudo make linux -B

            # Make log files
            - name: Make Log Files
              run: mkdir logs

            # Start Mercury
            - name: Start Mercury
              run: |
                cd bin
                powershell -command 'Start-Process .\mercury.exe -NoNewWindow -PassThru | ForEach-Object { $_.Id } > ..\pid.txt'

            # Run Python test cases
            - name: Python Test Runner
              run: |
                python --version || choco install python
                cd tests
                $output = python run.py
                echo $output
                if ($output.Split("`n")[-1] -like "*❌*") {
                  $pid = Get-Content ..\pid.txt
                  Stop-Process -Id $pid -Force
                  Start-Sleep -Seconds 5
                  exit 1
                }

            # Kill the server
            - name: Kill Server
              run: |
                $pid = Get-Content pid.txt
                Stop-Process -Id $pid -Force
                Start-Sleep -Seconds 5