name: Build (Linux)

on:
    workflow_dispatch:
    push:
        branches: ["main"]
        paths:
            - "src/**"
            - "lib/**"
    pull_request:
        branches: ["main"]
        paths:
            - "src/**"
            - "lib/**"

jobs:
    Build:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v4

            # Make log files
            - name: Make Log Files
              run: sudo mkdir logs

            # Start Mercury
            - name: Start Mercury
              run: |
                cd bin
                chmod +x ./mercury
                sudo ./mercury & echo $! > ../pid.txt

            # Run Python test cases
            - name: Python Test Runner
              run: |
                sudo apt install python3
                cd tests
                OUTPUT=$(python3 run.py)
                echo "$OUTPUT"
                if echo "$OUTPUT" | tail -n 2 | grep -q "Failure"; then
                  kill -INT $(cat ../pid.txt)
                  sleep 5
                  exit 1
                fi

            # Kill the server
            - name: Kill Server
              run: |
                kill -INT $(cat pid.txt)
                sleep 5 # Allow time to shutdown