name: Make Release

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  check-cache:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-24.04
    outputs:
      hit: ${{ steps.check.outputs.hit }}
    steps:
      - uses: actions/checkout@v5

      - name: Restore Linux Binaries
        uses: actions/cache@v4
        with:
          path: ./bin/mercury
          key: mercury-linux-binaries-${{ github.sha }}

      - name: Restore Windows Binaries
        uses: actions/cache@v4
        with:
          path: ./bin/mercury.exe
          key: mercury-windows-binaries-${{ github.sha }}
          enableCrossOsArchive: true

      - name: Restore Libs
        id: lib-cache
        uses: actions/cache@v4
        with:
          path: ./libs
          key: >-
            ${{ runner.os }}-artifacts-${{
              hashFiles(
                '**/build_tools/fetch_lib_pugixml.sh',
                '**/build_tools/build_lib_zlib.sh',
                '**/build_tools/build_lib_openssl.sh',
                '**/build_tools/build_lib_brotli.sh',
                '**/build_tools/build_lib_zstd.sh',
                '**/build_tools/dependencies.txt'
              )
            }}

      - name: Determine if both caches exist
        id: check
        run: |
          if [ -f "./bin/mercury" ] && [ -f "./bin/mercury.exe" ] && [ -d "./libs" ]; then
            echo "hit=true" >> $GITHUB_OUTPUT
          else
            echo "hit=false" >> $GITHUB_OUTPUT
          fi

  build:
    needs: check-cache
    if: github.ref == 'refs/heads/main' && needs.check-cache.outputs.hit == 'false'
    uses: ./.github/workflows/build.yml

  release:
    needs: [check-cache, build]
    if: >
      github.ref == 'refs/heads/main' &&
      (
        needs.check-cache.outputs.hit == 'true' ||
        always() && needs.build.result == 'success'
      )
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          ref: main

      - name: Set User
        run: |
          git config user.name "Mercury Actions Bot"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      # Download binaries & static libs
      - name: Restore Linux Binaries
        uses: actions/cache@v4
        with:
          path: ./bin/mercury
          key: mercury-linux-binaries-${{ github.sha }}

      - name: Restore Windows Binaries
        uses: actions/cache@v4
        with:
          path: ./bin/mercury.exe
          key: mercury-windows-binaries-${{ github.sha }}
          enableCrossOsArchive: true

      - name: Restore Cached Libs
        uses: actions/cache@v4
        with:
          path: ./libs
          key: >-
            ${{ runner.os }}-artifacts-${{
              hashFiles(
                '**/build_tools/fetch_lib_pugixml.sh',
                '**/build_tools/build_lib_zlib.sh',
                '**/build_tools/build_lib_openssl.sh',
                '**/build_tools/build_lib_brotli.sh',
                '**/build_tools/build_lib_zstd.sh',
                '**/build_tools/dependencies.txt'
              )
            }}

      # Make executables
      - name: Make Executable Shell Scripts
        run: |
          chmod +x ./build_tools/*.sh
          chmod +x ./build_tools/tools/*

      # Run release builder
      - name: Make Release
        run: |
          make -t all # Force to be up-to-date
          make lib_deps
          make release

      # Read version from version.txt
      - name: Extract Version
        id: version
        run: |
          VERSION=$(sed 's/^Mercury //' version.txt)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      # Delete existing release if it exists
      - name: Delete Existing Release If Exists
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION="${{ steps.version.outputs.version }}"

          echo "Cleaning up release and tag for $VERSION"

          # Delete release if it exists
          gh release delete "$VERSION" -y || echo "No release to delete"

          # Delete remote tag if it exists
          git push origin ":refs/tags/$VERSION" || echo "No remote tag to delete"

          # Delete local tag if it exists
          git tag -d "$VERSION" || echo "No local tag to delete"

          # Confirm cleanup
          gh release list --limit 5
          git ls-remote --tags origin | grep "$VERSION" || echo "Remote tag is gone"

      # Create GitHub Release
      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          SUMMARY_FILE=$(ls ./releases/SUMMARY_*.md | head -n1)
          TAR_FILE=$(ls ./releases/*.tar.gz | head -n1)
          ZIP_FILE=$(ls ./releases/*.zip | head -n1)

          # Determine if this is a pre-release (v0.*.*)
          if [[ "$VERSION" =~ ^v0\.[0-9]+\.[0-9]+$ ]]; then
            PRERELEASE="--prerelease"
          else
            PRERELEASE=""
          fi

          # Create release (tag is the version only, title keeps "Mercury vX.X.X")
          gh release create "$VERSION" "$TAR_FILE" "$ZIP_FILE" \
            --title "Mercury $VERSION" \
            --notes-file "$SUMMARY_FILE" \
            $PRERELEASE

      # Commit updated docs
      - name: Create Release Update Branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Create branch & commit
          git checkout -b release-update-${{ steps.version.outputs.version }}
          git add docs/releases.json docs/latest
          git commit -m "Update release metadata for ${{ steps.version.outputs.version }}" || echo "No changes to commit"
          git restore .
          git push origin HEAD

      - name: Create PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --title "[Website] Bump Release ${{ steps.version.outputs.version }}" \
            --body "Automated release bump for ${{ steps.version.outputs.version }}." \
            --base main \
            --head release-update-${{ steps.version.outputs.version }} \
            --label "website,repo,top-priority"

      - name: Approve and Merge PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=$(gh pr list --head release-update-${{ steps.version.outputs.version }} --json number -q '.[0].number')
          gh pr merge $PR_NUMBER --merge --admin

      - name: Delete Release Update Branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BRANCH="release-update-${{ steps.version.outputs.version }}"
          git push origin --delete "$BRANCH" || echo "Branch already deleted"