name: Test Runner (Linux)

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
    Build:
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@v4

            # Download binaries
            - uses: actions/download-artifact@v3
              with:
                name: mercury-binaries
                path: ./bin

            - name: Configure Ports & Enable IPv4 & IPv6
              run: |
                docRoot="./public/"
                port=8081
                sslPort=8082

                # Update conf/mercury.conf
                sed -i "s|<DocumentRoot>[[:space:]]*.*[[:space:]]*</DocumentRoot>|<DocumentRoot> $docRoot </DocumentRoot>|" conf/mercury.conf
                sed -i "s|<Port>[[:space:]]*[0-9]\+[[:space:]]*</Port>|<Port> $port </Port>|" conf/mercury.conf
                sed -i "s|<TLSPort>[[:space:]]*.*[[:space:]]*</TLSPort>|<TLSPort> $sslPort </TLSPort>|" conf/mercury.conf
                sed -i "s|<EnableIPv4>[[:space:]]*off[[:space:]]*</EnableIPv4>|<EnableIPv4> on </EnableIPv4>|" conf/mercury.conf
                sed -i "s|<EnableIPv6>[[:space:]]*off[[:space:]]*</EnableIPv6>|<EnableIPv6> on </EnableIPv6>|" conf/mercury.conf

                # Update tests/run.py
                sed -i "s|port[[:space:]]*=[[:space:]]*.*|port = $port|" tests/run.py
                sed -i "s|ssl_port[[:space:]]*=[[:space:]]*.*|ssl_port = $sslPort|" tests/run.py

            # Make log files
            - name: Make Log Files
              run: sudo mkdir logs

            # Make TLS cert
            - name: Make TLS Cert
              run: |
                mkdir conf/ssl
                openssl req -x509 \
                  -newkey rsa:4096 \
                  -keyout conf/ssl/key.pem \
                  -out conf/ssl/cert.pem \
                  -sha256 \
                  -days 1 \
                  -nodes \
                  -subj "/C=XX/ST=New York/L=NYC/O=The Mercury Project/OU=GitHub Action Runner/CN=The Mercury Developers"

            # Start Mercury
            - name: Start Mercury
              run: |
                cd bin
                sudo chmod +x ./mercury
                sudo ./mercury & echo $! > ../pid.txt

            # Run Python test cases
            - name: Python Test Runner
              run: |
                cd tests
                OUTPUT=$(python3 run.py)
                echo "$OUTPUT"
                if echo "$OUTPUT" | tail -n 2 | grep -q "Failure"; then
                  kill -INT $(cat ../pid.txt)
                  sleep 5
                  exit 1
                fi

            # Kill the server
            - name: Kill Server
              run: |
                kill -INT $(cat pid.txt)
                sleep 5 # Allow time to shutdown