name: Test Runner (Linux)

on:
    workflow_dispatch:
    push:
        branches: ["main"]
        paths:
            - "src/**"
            - "lib/**"
    pull_request:
        branches: ["main"]
        paths:
            - "src/**"
            - "lib/**"

jobs:
    Build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            # Mark artifacts for caching
            - name: Cache Library Artifacts
              uses: actions/cache@v4
              with:
                path: ./static_libs
                key: ${{ runner.os }}-artifacts-linux-${{ hashFiles('**/build_tools/install_deps.sh') }}

            # Make executables
            - name: Make Executable Shell Ccripts
              run: sudo chmod +x ./build_tools/*.sh

            # Install deps & build static binaries
            - name: Install Deps & Build Libs
              run: |
                make static_deps
                if [ ! -d static_libs ] || [ -z "$(ls -A static_libs)" ]; then
                  make runners_libs_linux
                fi

            # Build
            - name: Build Mercury Binaries
              run: sudo make linux -B

            - name: Configure Ports & Enable IPv4 & IPv6
              run: |
                docRoot="./public/"
                port=8081
                sslPort=8082

                # Update conf/mercury.conf
                sed -i "s|<DocumentRoot>[[:space:]]*.*[[:space:]]*</DocumentRoot>|<DocumentRoot> $docRoot </DocumentRoot>|" conf/mercury.conf
                sed -i "s|<Port>[[:space:]]*[0-9]\+[[:space:]]*</Port>|<Port> $port </Port>|" conf/mercury.conf
                sed -i "s|<TLSPort>[[:space:]]*.*[[:space:]]*</TLSPort>|<TLSPort> $sslPort </TLSPort>|" conf/mercury.conf
                sed -i "s|<EnableIPv4>[[:space:]]*off[[:space:]]*</EnableIPv4>|<EnableIPv4> on </EnableIPv4>|" conf/mercury.conf
                sed -i "s|<EnableIPv6>[[:space:]]*off[[:space:]]*</EnableIPv6>|<EnableIPv6> on </EnableIPv6>|" conf/mercury.conf

                # Update tests/run.py
                sed -i "s|port[[:space:]]*=[[:space:]]*.*|port = $port|" tests/run.py
                sed -i "s|ssl_port[[:space:]]*=[[:space:]]*.*|ssl_port = $sslPort|" tests/run.py

            # Make log files
            - name: Make Log Files
              run: sudo mkdir logs

            # Make TLS cert
            - name: Make TLS Cert
              run: |
                mkdir conf/ssl
                openssl req -x509 \
                  -newkey rsa:4096 \
                  -keyout conf/ssl/key.pem \
                  -out conf/ssl/cert.pem \
                  -sha256 \
                  -days 1 \
                  -nodes \
                  -subj "/C=XX/ST=New York/L=NYC/O=The Mercury Project/OU=GitHub Action Runner/CN=The Mercury Developers"

            # Start Mercury
            - name: Start Mercury
              run: |
                cd bin
                sudo chmod +x ./mercury
                sudo ./mercury & echo $! > ../pid.txt

            # Run Python test cases
            - name: Python Test Runner
              run: |
                cd tests
                OUTPUT=$(python3 run.py)
                echo "$OUTPUT"
                if echo "$OUTPUT" | tail -n 2 | grep -q "Failure"; then
                  kill -INT $(cat ../pid.txt)
                  sleep 5
                  exit 1
                fi

            # Kill the server
            - name: Kill Server
              run: |
                kill -INT $(cat pid.txt)
                sleep 5 # Allow time to shutdown