name: Test Runner (Linux)

on:
  workflow_call:
    inputs:
      artifact-name:
        required: true
        type: string

jobs:
  Test-Linux:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5

      # Download binaries
      - name: Cache Linux Binaries
        uses: actions/cache@v4
        with:
          path: ./bin/mercury
          key: mercury-linux-binaries-${{ github.sha }}

      - name: Copy Default Config
        run: |
          cp conf/default/mimes.conf conf/mimes.conf
          cp conf/default/mercury.conf conf/mercury.conf

      - name: Install Deps
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: php-cgi python3-zstandard python3-brotli
          version: 1.0

      # Make TLS cert
      - name: Make TLS Cert
        run: |
          openssl req -x509 \
            -newkey rsa:4096 \
            -keyout conf/ssl/key.pem \
            -out conf/ssl/cert.pem \
            -sha256 \
            -days 1 \
            -nodes \
            -subj "/C=XX/ST=New York/L=NYC/O=The Mercury Project/OU=GitHub Action Runner/CN=The Mercury Developers"

      # Run Python test cases
      - name: Python Test Runner
        run: python3 tests/run.py
